import random

def uniquePercentage(lower, upper, numTrial):
    """
    Input:
	lower: an integer that is the lower bound of the range.
	Upper: an integer that is the upper bound of the range.
	numTrail: the number of times of invoking random.randint(lower,upper)
    Output:
	Return the percentage of the numbers in [lower,upper] generated by random.randint(lower,upper)
    """

    setNum = set()
    for n in range(numTrial):
        setNum.add(random.randint(lower,upper))
    return len(setNum)*100/(upper-lower+1)

for n in range(100,251):
    print(n, uniquePercentage(1,100,n))
